//
//  File.swift
//  WeatherApp
//
//  Created by Pursuit on 1/31/20.
//  Copyright © 2020 David Rifkin. All rights reserved.
//

import Foundation

// want to encode the data not the string... 
//
//

//      https://api.darksky.net/forecast/[key]/[latitude],[longitude]

/*
 {
     "latitude": 37.8267,
     "longitude": -122.4233,
     "timezone": "America/Los_Angeles",
     "currently": {
         "time": 1580843958,
         "summary": "Clear",
         "icon": "clear-day",
         "nearestStormDistance": 434,
         "nearestStormBearing": 5,
         "precipIntensity": 0,
         "precipProbability": 0,
         "temperature": 51.53,
         "apparentTemperature": 51.85,
         "dewPoint": 23.72,
         "humidity": 0.34,
         "pressure": 1025.7,
         "windSpeed": 10.08,
         "windGust": 16.6,
         "windBearing": 2,
         "cloudCover": 0.15,
         "uvIndex": 2,
         "visibility": 10,
         "ozone": 364.3
     },
     "minutely": {
         "summary": "Clear for the hour.",
         "icon": "clear-day",
         "data": [
             {
                 "time": 1580843940,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844000,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844060,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844120,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844180,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844240,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844300,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844360,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844420,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844480,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844540,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844600,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844660,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844720,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844780,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844840,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844900,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580844960,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845020,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845080,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845140,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845200,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845260,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845320,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845380,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845440,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845500,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845560,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845620,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845680,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845740,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845800,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845860,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845920,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580845980,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580846040,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580846100,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580846160,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580846220,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580846280,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580846340,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580846400,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580846460,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580846520,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580846580,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580846640,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580846700,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580846760,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580846820,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580846880,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580846940,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580847000,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580847060,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580847120,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580847180,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580847240,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580847300,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580847360,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580847420,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580847480,
                 "precipIntensity": 0,
                 "precipProbability": 0
             },
             {
                 "time": 1580847540,
                 "precipIntensity": 0,
                 "precipProbability": 0
             }
         ]
     },
     "hourly": {
         "summary": "Clear throughout the day.",
         "icon": "clear-day",
         "data": [
             {
                 "time": 1580842800,
                 "summary": "Clear",
                 "icon": "clear-day",
                 "precipIntensity": 0.0019,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 50.97,
                 "apparentTemperature": 50.97,
                 "dewPoint": 24.11,
                 "humidity": 0.35,
                 "pressure": 1025.9,
                 "windSpeed": 10.32,
                 "windGust": 17.41,
                 "windBearing": 2,
                 "cloudCover": 0.05,
                 "uvIndex": 2,
                 "visibility": 10,
                 "ozone": 364.4
             },
             {
                 "time": 1580846400,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-day",
                 "precipIntensity": 0.0004,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 52.65,
                 "apparentTemperature": 52.65,
                 "dewPoint": 23,
                 "humidity": 0.31,
                 "pressure": 1025.1,
                 "windSpeed": 9.41,
                 "windGust": 14.87,
                 "windBearing": 2,
                 "cloudCover": 0.4,
                 "uvIndex": 2,
                 "visibility": 10,
                 "ozone": 364.1
             },
             {
                 "time": 1580850000,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-day",
                 "precipIntensity": 0.0007,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 54.33,
                 "apparentTemperature": 54.33,
                 "dewPoint": 23.47,
                 "humidity": 0.3,
                 "pressure": 1024.7,
                 "windSpeed": 9.05,
                 "windGust": 13.83,
                 "windBearing": 1,
                 "cloudCover": 0.34,
                 "uvIndex": 2,
                 "visibility": 10,
                 "ozone": 364
             },
             {
                 "time": 1580853600,
                 "summary": "Clear",
                 "icon": "clear-day",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 55.4,
                 "apparentTemperature": 55.4,
                 "dewPoint": 26.2,
                 "humidity": 0.32,
                 "pressure": 1024,
                 "windSpeed": 9.02,
                 "windGust": 13.81,
                 "windBearing": 358,
                 "cloudCover": 0.07,
                 "uvIndex": 2,
                 "visibility": 10,
                 "ozone": 364.7
             },
             {
                 "time": 1580857200,
                 "summary": "Clear",
                 "icon": "clear-day",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 56.34,
                 "apparentTemperature": 56.34,
                 "dewPoint": 28.5,
                 "humidity": 0.34,
                 "pressure": 1023.8,
                 "windSpeed": 8.71,
                 "windGust": 12.75,
                 "windBearing": 346,
                 "cloudCover": 0.05,
                 "uvIndex": 1,
                 "visibility": 10,
                 "ozone": 365.7
             },
             {
                 "time": 1580860800,
                 "summary": "Clear",
                 "icon": "clear-day",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 56.55,
                 "apparentTemperature": 56.55,
                 "dewPoint": 31.52,
                 "humidity": 0.38,
                 "pressure": 1023.5,
                 "windSpeed": 8.28,
                 "windGust": 11.98,
                 "windBearing": 337,
                 "cloudCover": 0.05,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 365.8
             },
             {
                 "time": 1580864400,
                 "summary": "Clear",
                 "icon": "clear-day",
                 "precipIntensity": 0.0016,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 55.16,
                 "apparentTemperature": 55.16,
                 "dewPoint": 34.77,
                 "humidity": 0.46,
                 "pressure": 1023.9,
                 "windSpeed": 7.59,
                 "windGust": 11.4,
                 "windBearing": 325,
                 "cloudCover": 0.05,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 364.6
             },
             {
                 "time": 1580868000,
                 "summary": "Clear",
                 "icon": "clear-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 53.09,
                 "apparentTemperature": 53.09,
                 "dewPoint": 37.68,
                 "humidity": 0.56,
                 "pressure": 1023.9,
                 "windSpeed": 6.9,
                 "windGust": 11.01,
                 "windBearing": 315,
                 "cloudCover": 0.07,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 362.5
             },
             {
                 "time": 1580871600,
                 "summary": "Clear",
                 "icon": "clear-night",
                 "precipIntensity": 0.0003,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 51.76,
                 "apparentTemperature": 51.76,
                 "dewPoint": 39.44,
                 "humidity": 0.63,
                 "pressure": 1024.5,
                 "windSpeed": 6.35,
                 "windGust": 9.41,
                 "windBearing": 312,
                 "cloudCover": 0.08,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 360.5
             },
             {
                 "time": 1580875200,
                 "summary": "Clear",
                 "icon": "clear-night",
                 "precipIntensity": 0.0013,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 51.02,
                 "apparentTemperature": 51.02,
                 "dewPoint": 39.77,
                 "humidity": 0.65,
                 "pressure": 1025,
                 "windSpeed": 5.61,
                 "windGust": 7.69,
                 "windBearing": 317,
                 "cloudCover": 0.19,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 358.9
             },
             {
                 "time": 1580878800,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 50.57,
                 "apparentTemperature": 50.57,
                 "dewPoint": 39.62,
                 "humidity": 0.66,
                 "pressure": 1024.8,
                 "windSpeed": 5.13,
                 "windGust": 6.57,
                 "windBearing": 321,
                 "cloudCover": 0.4,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 357.4
             },
             {
                 "time": 1580882400,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 50.17,
                 "apparentTemperature": 50.17,
                 "dewPoint": 39.4,
                 "humidity": 0.66,
                 "pressure": 1025,
                 "windSpeed": 4.76,
                 "windGust": 5.5,
                 "windBearing": 328,
                 "cloudCover": 0.51,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 356.5
             },
             {
                 "time": 1580886000,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 49.5,
                 "apparentTemperature": 47.97,
                 "dewPoint": 39.4,
                 "humidity": 0.68,
                 "pressure": 1025.2,
                 "windSpeed": 4.48,
                 "windGust": 5.07,
                 "windBearing": 346,
                 "cloudCover": 0.52,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 356.8
             },
             {
                 "time": 1580889600,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-night",
                 "precipIntensity": 0.0013,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 48.92,
                 "apparentTemperature": 47.33,
                 "dewPoint": 39.57,
                 "humidity": 0.7,
                 "pressure": 1025.4,
                 "windSpeed": 4.41,
                 "windGust": 5,
                 "windBearing": 358,
                 "cloudCover": 0.52,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 357.6
             },
             {
                 "time": 1580893200,
                 "summary": "Clear",
                 "icon": "clear-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 48.32,
                 "apparentTemperature": 46.87,
                 "dewPoint": 38.11,
                 "humidity": 0.68,
                 "pressure": 1024.8,
                 "windSpeed": 4.08,
                 "windGust": 4.08,
                 "windBearing": 63,
                 "cloudCover": 0.28,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 357.7
             },
             {
                 "time": 1580896800,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 47.75,
                 "apparentTemperature": 46.28,
                 "dewPoint": 37.88,
                 "humidity": 0.68,
                 "pressure": 1025,
                 "windSpeed": 3.99,
                 "windGust": 3.99,
                 "windBearing": 68,
                 "cloudCover": 0.35,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 357
             },
             {
                 "time": 1580900400,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 47.19,
                 "apparentTemperature": 45.68,
                 "dewPoint": 37.47,
                 "humidity": 0.69,
                 "pressure": 1025.2,
                 "windSpeed": 3.92,
                 "windGust": 3.92,
                 "windBearing": 83,
                 "cloudCover": 0.44,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 355.6
             },
             {
                 "time": 1580904000,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 46.42,
                 "apparentTemperature": 44.78,
                 "dewPoint": 37.07,
                 "humidity": 0.7,
                 "pressure": 1025.5,
                 "windSpeed": 3.94,
                 "windGust": 3.96,
                 "windBearing": 88,
                 "cloudCover": 0.48,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 353.8
             },
             {
                 "time": 1580907600,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 45.48,
                 "apparentTemperature": 43.5,
                 "dewPoint": 36.83,
                 "humidity": 0.72,
                 "pressure": 1025.3,
                 "windSpeed": 4.19,
                 "windGust": 4.21,
                 "windBearing": 78,
                 "cloudCover": 0.43,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 351.1
             },
             {
                 "time": 1580911200,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 44.72,
                 "apparentTemperature": 42.34,
                 "dewPoint": 36.71,
                 "humidity": 0.73,
                 "pressure": 1024.8,
                 "windSpeed": 4.55,
                 "windGust": 4.57,
                 "windBearing": 58,
                 "cloudCover": 0.34,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 348
             },
             {
                 "time": 1580914800,
                 "summary": "Clear",
                 "icon": "clear-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 44.93,
                 "apparentTemperature": 42.42,
                 "dewPoint": 36.98,
                 "humidity": 0.74,
                 "pressure": 1024.5,
                 "windSpeed": 4.78,
                 "windGust": 4.78,
                 "windBearing": 49,
                 "cloudCover": 0.27,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 345.7
             },
             {
                 "time": 1580918400,
                 "summary": "Clear",
                 "icon": "clear-day",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 46.42,
                 "apparentTemperature": 44.21,
                 "dewPoint": 37.33,
                 "humidity": 0.7,
                 "pressure": 1025,
                 "windSpeed": 4.72,
                 "windGust": 4.72,
                 "windBearing": 60,
                 "cloudCover": 0.25,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 345.4
             },
             {
                 "time": 1580922000,
                 "summary": "Clear",
                 "icon": "clear-day",
                 "precipIntensity": 0.0002,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 48.67,
                 "apparentTemperature": 46.97,
                 "dewPoint": 37.15,
                 "humidity": 0.64,
                 "pressure": 1025.7,
                 "windSpeed": 4.52,
                 "windGust": 4.71,
                 "windBearing": 65,
                 "cloudCover": 0.26,
                 "uvIndex": 1,
                 "visibility": 10,
                 "ozone": 346
             },
             {
                 "time": 1580925600,
                 "summary": "Clear",
                 "icon": "clear-day",
                 "precipIntensity": 0.0003,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 50.8,
                 "apparentTemperature": 50.8,
                 "dewPoint": 36.86,
                 "humidity": 0.59,
                 "pressure": 1026,
                 "windSpeed": 4.39,
                 "windGust": 4.72,
                 "windBearing": 48,
                 "cloudCover": 0.25,
                 "uvIndex": 1,
                 "visibility": 10,
                 "ozone": 344.9
             },
             {
                 "time": 1580929200,
                 "summary": "Clear",
                 "icon": "clear-day",
                 "precipIntensity": 0.0003,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 53.19,
                 "apparentTemperature": 53.19,
                 "dewPoint": 36.71,
                 "humidity": 0.53,
                 "pressure": 1025.6,
                 "windSpeed": 4.34,
                 "windGust": 4.75,
                 "windBearing": 17,
                 "cloudCover": 0.27,
                 "uvIndex": 2,
                 "visibility": 10,
                 "ozone": 340.6
             },
             {
                 "time": 1580932800,
                 "summary": "Clear",
                 "icon": "clear-day",
                 "precipIntensity": 0.0002,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 55.68,
                 "apparentTemperature": 55.68,
                 "dewPoint": 36.62,
                 "humidity": 0.49,
                 "pressure": 1024.8,
                 "windSpeed": 4.34,
                 "windGust": 4.82,
                 "windBearing": 336,
                 "cloudCover": 0.28,
                 "uvIndex": 3,
                 "visibility": 10,
                 "ozone": 334.7
             },
             {
                 "time": 1580936400,
                 "summary": "Clear",
                 "icon": "clear-day",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 57.76,
                 "apparentTemperature": 57.76,
                 "dewPoint": 37.1,
                 "humidity": 0.46,
                 "pressure": 1024.1,
                 "windSpeed": 4.55,
                 "windGust": 5.16,
                 "windBearing": 315,
                 "cloudCover": 0.27,
                 "uvIndex": 3,
                 "visibility": 10,
                 "ozone": 329.5
             },
             {
                 "time": 1580940000,
                 "summary": "Clear",
                 "icon": "clear-day",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 58.87,
                 "apparentTemperature": 58.87,
                 "dewPoint": 38.86,
                 "humidity": 0.47,
                 "pressure": 1023.3,
                 "windSpeed": 5.19,
                 "windGust": 5.39,
                 "windBearing": 340,
                 "cloudCover": 0.2,
                 "uvIndex": 2,
                 "visibility": 10,
                 "ozone": 326.2
             },
             {
                 "time": 1580943600,
                 "summary": "Clear",
                 "icon": "clear-day",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 59.12,
                 "apparentTemperature": 59.12,
                 "dewPoint": 41.36,
                 "humidity": 0.52,
                 "pressure": 1022.7,
                 "windSpeed": 6.04,
                 "windGust": 6.04,
                 "windBearing": 260,
                 "cloudCover": 0.09,
                 "uvIndex": 1,
                 "visibility": 10,
                 "ozone": 323.5
             },
             {
                 "time": 1580947200,
                 "summary": "Clear",
                 "icon": "clear-day",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 58.44,
                 "apparentTemperature": 58.44,
                 "dewPoint": 43.92,
                 "humidity": 0.58,
                 "pressure": 1022.4,
                 "windSpeed": 6.69,
                 "windGust": 6.69,
                 "windBearing": 275,
                 "cloudCover": 0,
                 "uvIndex": 1,
                 "visibility": 10,
                 "ozone": 320.8
             },
             {
                 "time": 1580950800,
                 "summary": "Clear",
                 "icon": "clear-day",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 56.81,
                 "apparentTemperature": 56.81,
                 "dewPoint": 46.29,
                 "humidity": 0.68,
                 "pressure": 1022.3,
                 "windSpeed": 6.98,
                 "windGust": 6.98,
                 "windBearing": 275,
                 "cloudCover": 0.07,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 318.1
             },
             {
                 "time": 1580954400,
                 "summary": "Clear",
                 "icon": "clear-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 54.68,
                 "apparentTemperature": 54.68,
                 "dewPoint": 47.09,
                 "humidity": 0.75,
                 "pressure": 1022.4,
                 "windSpeed": 7.06,
                 "windGust": 7.54,
                 "windBearing": 283,
                 "cloudCover": 0.15,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 315.4
             },
             {
                 "time": 1580958000,
                 "summary": "Clear",
                 "icon": "clear-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 52.93,
                 "apparentTemperature": 52.93,
                 "dewPoint": 47.34,
                 "humidity": 0.81,
                 "pressure": 1022.5,
                 "windSpeed": 6.82,
                 "windGust": 8.31,
                 "windBearing": 279,
                 "cloudCover": 0.21,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 313
             },
             {
                 "time": 1580961600,
                 "summary": "Clear",
                 "icon": "clear-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 52.15,
                 "apparentTemperature": 52.15,
                 "dewPoint": 47.46,
                 "humidity": 0.84,
                 "pressure": 1022.8,
                 "windSpeed": 6.15,
                 "windGust": 7.5,
                 "windBearing": 294,
                 "cloudCover": 0.21,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 311.1
             },
             {
                 "time": 1580965200,
                 "summary": "Clear",
                 "icon": "clear-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 51.95,
                 "apparentTemperature": 51.95,
                 "dewPoint": 47.45,
                 "humidity": 0.85,
                 "pressure": 1023.3,
                 "windSpeed": 5.2,
                 "windGust": 5.98,
                 "windBearing": 333,
                 "cloudCover": 0.2,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 309.3
             },
             {
                 "time": 1580968800,
                 "summary": "Clear",
                 "icon": "clear-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 51.71,
                 "apparentTemperature": 51.71,
                 "dewPoint": 47.17,
                 "humidity": 0.84,
                 "pressure": 1023.7,
                 "windSpeed": 4.4,
                 "windGust": 5.02,
                 "windBearing": 272,
                 "cloudCover": 0.19,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 307.3
             },
             {
                 "time": 1580972400,
                 "summary": "Clear",
                 "icon": "clear-night",
                 "precipIntensity": 0,
                 "precipProbability": 0,
                 "temperature": 51.36,
                 "apparentTemperature": 51.36,
                 "dewPoint": 46.62,
                 "humidity": 0.84,
                 "pressure": 1023.8,
                 "windSpeed": 3.85,
                 "windGust": 4.49,
                 "windBearing": 274,
                 "cloudCover": 0.24,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 304.6
             },
             {
                 "time": 1580976000,
                 "summary": "Clear",
                 "icon": "clear-night",
                 "precipIntensity": 0.0003,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 50.96,
                 "apparentTemperature": 50.96,
                 "dewPoint": 46.01,
                 "humidity": 0.83,
                 "pressure": 1023.8,
                 "windSpeed": 3.43,
                 "windGust": 4.12,
                 "windBearing": 315,
                 "cloudCover": 0.31,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 301.5
             },
             {
                 "time": 1580979600,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-night",
                 "precipIntensity": 0.0004,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 50.66,
                 "apparentTemperature": 50.66,
                 "dewPoint": 45.57,
                 "humidity": 0.83,
                 "pressure": 1023.6,
                 "windSpeed": 3.17,
                 "windGust": 3.93,
                 "windBearing": 355,
                 "cloudCover": 0.36,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 298.9
             },
             {
                 "time": 1580983200,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-night",
                 "precipIntensity": 0.0005,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 50.25,
                 "apparentTemperature": 50.25,
                 "dewPoint": 45.29,
                 "humidity": 0.83,
                 "pressure": 1023.4,
                 "windSpeed": 3.19,
                 "windGust": 3.82,
                 "windBearing": 28,
                 "cloudCover": 0.37,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 297.1
             },
             {
                 "time": 1580986800,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-night",
                 "precipIntensity": 0.0005,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 49.76,
                 "apparentTemperature": 49.08,
                 "dewPoint": 45,
                 "humidity": 0.84,
                 "pressure": 1023.1,
                 "windSpeed": 3.38,
                 "windGust": 3.79,
                 "windBearing": 34,
                 "cloudCover": 0.37,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 295.6
             },
             {
                 "time": 1580990400,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-night",
                 "precipIntensity": 0.0006,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 49.22,
                 "apparentTemperature": 48.36,
                 "dewPoint": 44.69,
                 "humidity": 0.84,
                 "pressure": 1022.8,
                 "windSpeed": 3.5,
                 "windGust": 3.79,
                 "windBearing": 18,
                 "cloudCover": 0.37,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 294.7
             },
             {
                 "time": 1580994000,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-night",
                 "precipIntensity": 0.0005,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 48.42,
                 "apparentTemperature": 47.46,
                 "dewPoint": 44.26,
                 "humidity": 0.85,
                 "pressure": 1022.7,
                 "windSpeed": 3.47,
                 "windGust": 3.78,
                 "windBearing": 17,
                 "cloudCover": 0.38,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 294
             },
             {
                 "time": 1580997600,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-night",
                 "precipIntensity": 0.0003,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 47.81,
                 "apparentTemperature": 46.84,
                 "dewPoint": 43.9,
                 "humidity": 0.86,
                 "pressure": 1022.8,
                 "windSpeed": 3.4,
                 "windGust": 3.78,
                 "windBearing": 16,
                 "cloudCover": 0.38,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 293.8
             },
             {
                 "time": 1581001200,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-night",
                 "precipIntensity": 0.0002,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 47.67,
                 "apparentTemperature": 46.78,
                 "dewPoint": 43.88,
                 "humidity": 0.87,
                 "pressure": 1023,
                 "windSpeed": 3.28,
                 "windGust": 3.8,
                 "windBearing": 12,
                 "cloudCover": 0.38,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 293.8
             },
             {
                 "time": 1581004800,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-day",
                 "precipIntensity": 0.0002,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 48.1,
                 "apparentTemperature": 47.48,
                 "dewPoint": 44.28,
                 "humidity": 0.87,
                 "pressure": 1023.2,
                 "windSpeed": 3.05,
                 "windGust": 3.89,
                 "windBearing": 28,
                 "cloudCover": 0.39,
                 "uvIndex": 0,
                 "visibility": 10,
                 "ozone": 294.2
             },
             {
                 "time": 1581008400,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-day",
                 "precipIntensity": 0.0002,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 48.81,
                 "apparentTemperature": 48.81,
                 "dewPoint": 44.94,
                 "humidity": 0.86,
                 "pressure": 1023.4,
                 "windSpeed": 2.8,
                 "windGust": 4.04,
                 "windBearing": 44,
                 "cloudCover": 0.39,
                 "uvIndex": 1,
                 "visibility": 10,
                 "ozone": 294.8
             },
             {
                 "time": 1581012000,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-day",
                 "precipIntensity": 0.0003,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 49.85,
                 "apparentTemperature": 49.85,
                 "dewPoint": 45.86,
                 "humidity": 0.86,
                 "pressure": 1023.4,
                 "windSpeed": 2.83,
                 "windGust": 4.29,
                 "windBearing": 38,
                 "cloudCover": 0.39,
                 "uvIndex": 2,
                 "visibility": 10,
                 "ozone": 295.4
             },
             {
                 "time": 1581015600,
                 "summary": "Partly Cloudy",
                 "icon": "partly-cloudy-day",
                 "precipIntensity": 0.0002,
                 "precipProbability": 0.01,
                 "precipType": "rain",
                 "temperature": 51.4,
                 "apparentTemperature": 51.4,
                 "dewPoint": 46.56,
                 "humidity": 0.83,
                 "pressure": 1023.1,
                 "windSpeed": 3.28,
                 "windGust": 4.8,
                 "windBearing": 30,
                 "cloudCover": 0.36,
                 "uvIndex": 3,
                 "visibility": 10,
                 "ozone": 295.9
             }
         ]
     },
     "daily": {
         "summary": "No precipitation throughout the week.",
         "icon": "clear-day",
         "data": [
             {
                 "time": 1580803200,
                 "summary": "Clear throughout the day.",
                 "icon": "clear-day",
                 "sunriseTime": 1580829180,
                 "sunsetTime": 1580866620,
                 "moonPhase": 0.35,
                 "precipIntensity": 0.0007,
                 "precipIntensityMax": 0.0025,
                 "precipIntensityMaxTime": 1580843940,
                 "precipProbability": 0.09,
                 "precipType": "rain",
                 "temperatureHigh": 57.13,
                 "temperatureHighTime": 1580859780,
                 "temperatureLow": 44.18,
                 "temperatureLowTime": 1580912400,
                 "apparentTemperatureHigh": 56.63,
                 "apparentTemperatureHighTime": 1580859780,
                 "apparentTemperatureLow": 42.19,
                 "apparentTemperatureLowTime": 1580912940,
                 "dewPoint": 29.74,
                 "humidity": 0.46,
                 "pressure": 1024.6,
                 "windSpeed": 9.33,
                 "windGust": 22.27,
                 "windGustTime": 1580818620,
                 "windBearing": 352,
                 "cloudCover": 0.13,
                 "uvIndex": 2,
                 "uvIndexTime": 1580848440,
                 "visibility": 10,
                 "ozone": 361.8,
                 "temperatureMin": 45.2,
                 "temperatureMinTime": 1580825460,
                 "temperatureMax": 57.13,
                 "temperatureMaxTime": 1580859780,
                 "apparentTemperatureMin": 40.01,
                 "apparentTemperatureMinTime": 1580824680,
                 "apparentTemperatureMax": 56.63,
                 "apparentTemperatureMaxTime": 1580859780
             },
             {
                 "time": 1580889600,
                 "summary": "Clear throughout the day.",
                 "icon": "clear-day",
                 "sunriseTime": 1580915520,
                 "sunsetTime": 1580953080,
                 "moonPhase": 0.39,
                 "precipIntensity": 0.0001,
                 "precipIntensityMax": 0.0013,
                 "precipIntensityMaxTime": 1580889600,
                 "precipProbability": 0.08,
                 "precipType": "rain",
                 "temperatureHigh": 59.64,
                 "temperatureHighTime": 1580942820,
                 "temperatureLow": 47.16,
                 "temperatureLowTime": 1581000420,
                 "apparentTemperatureHigh": 59.14,
                 "apparentTemperatureHighTime": 1580942820,
                 "apparentTemperatureLow": 46.72,
                 "apparentTemperatureLowTime": 1580999820,
                 "dewPoint": 40.8,
                 "humidity": 0.68,
                 "pressure": 1024.2,
                 "windSpeed": 4.94,
                 "windGust": 8.31,
                 "windGustTime": 1580958000,
                 "windBearing": 335,
                 "cloudCover": 0.26,
                 "uvIndex": 3,
                 "uvIndexTime": 1580934660,
                 "visibility": 10,
                 "ozone": 332.9,
                 "temperatureMin": 44.18,
                 "temperatureMinTime": 1580912400,
                 "temperatureMax": 59.64,
                 "temperatureMaxTime": 1580942820,
                 "apparentTemperatureMin": 42.19,
                 "apparentTemperatureMinTime": 1580912940,
                 "apparentTemperatureMax": 59.14,
                 "apparentTemperatureMaxTime": 1580942820
             },
             {
                 "time": 1580976000,
                 "summary": "Partly cloudy throughout the day.",
                 "icon": "partly-cloudy-day",
                 "sunriseTime": 1581001860,
                 "sunsetTime": 1581039540,
                 "moonPhase": 0.42,
                 "precipIntensity": 0.0003,
                 "precipIntensityMax": 0.0006,
                 "precipIntensityMaxTime": 1580989740,
                 "precipProbability": 0.11,
                 "precipType": "rain",
                 "temperatureHigh": 58.74,
                 "temperatureHighTime": 1581031860,
                 "temperatureLow": 47.81,
                 "temperatureLowTime": 1581087000,
                 "apparentTemperatureHigh": 58.24,
                 "apparentTemperatureHighTime": 1581031860,
                 "apparentTemperatureLow": 47.8,
                 "apparentTemperatureLowTime": 1581084120,
                 "dewPoint": 47.15,
                 "humidity": 0.84,
                 "pressure": 1022.1,
                 "windSpeed": 4.04,
                 "windGust": 6.31,
                 "windGustTime": 1581035160,
                 "windBearing": 326,
                 "cloudCover": 0.31,
                 "uvIndex": 3,
                 "uvIndexTime": 1581020820,
                 "visibility": 10,
                 "ozone": 294.1,
                 "temperatureMin": 47.16,
                 "temperatureMinTime": 1581000420,
                 "temperatureMax": 58.74,
                 "temperatureMaxTime": 1581031860,
                 "apparentTemperatureMin": 46.72,
                 "apparentTemperatureMinTime": 1580999820,
                 "apparentTemperatureMax": 58.24,
                 "apparentTemperatureMaxTime": 1581031860
             },
             {
                 "time": 1581062400,
                 "summary": "Clear throughout the day.",
                 "icon": "clear-day",
                 "sunriseTime": 1581088200,
                 "sunsetTime": 1581126060,
                 "moonPhase": 0.46,
                 "precipIntensity": 0.0003,
                 "precipIntensityMax": 0.0009,
                 "precipIntensityMaxTime": 1581067560,
                 "precipProbability": 0.11,
                 "precipType": "rain",
                 "temperatureHigh": 60.63,
                 "temperatureHighTime": 1581116580,
                 "temperatureLow": 47.22,
                 "temperatureLowTime": 1581172320,
                 "apparentTemperatureHigh": 60.13,
                 "apparentTemperatureHighTime": 1581116580,
                 "apparentTemperatureLow": 47.71,
                 "apparentTemperatureLowTime": 1581176460,
                 "dewPoint": 48.91,
                 "humidity": 0.86,
                 "pressure": 1020.9,
                 "windSpeed": 4.19,
                 "windGust": 7.68,
                 "windGustTime": 1581126660,
                 "windBearing": 320,
                 "cloudCover": 0.25,
                 "uvIndex": 3,
                 "uvIndexTime": 1581107160,
                 "visibility": 10,
                 "ozone": 295.6,
                 "temperatureMin": 47.81,
                 "temperatureMinTime": 1581087000,
                 "temperatureMax": 60.63,
                 "temperatureMaxTime": 1581116580,
                 "apparentTemperatureMin": 47.8,
                 "apparentTemperatureMinTime": 1581084120,
                 "apparentTemperatureMax": 60.13,
                 "apparentTemperatureMaxTime": 1581116580
             },
             {
                 "time": 1581148800,
                 "summary": "Clear throughout the day.",
                 "icon": "clear-day",
                 "sunriseTime": 1581174540,
                 "sunsetTime": 1581212520,
                 "moonPhase": 0.5,
                 "precipIntensity": 0.0001,
                 "precipIntensityMax": 0.0002,
                 "precipIntensityMaxTime": 1581227460,
                 "precipProbability": 0.05,
                 "precipType": "rain",
                 "temperatureHigh": 59.35,
                 "temperatureHighTime": 1581202860,
                 "temperatureLow": 46.14,
                 "temperatureLowTime": 1581259500,
                 "apparentTemperatureHigh": 58.85,
                 "apparentTemperatureHighTime": 1581202860,
                 "apparentTemperatureLow": 40.99,
                 "apparentTemperatureLowTime": 1581260460,
                 "dewPoint": 48.32,
                 "humidity": 0.86,
                 "pressure": 1017.7,
                 "windSpeed": 4.68,
                 "windGust": 10.09,
                 "windGustTime": 1581205920,
                 "windBearing": 330,
                 "cloudCover": 0.12,
                 "uvIndex": 3,
                 "uvIndexTime": 1581192360,
                 "visibility": 10,
                 "ozone": 302,
                 "temperatureMin": 47.22,
                 "temperatureMinTime": 1581172320,
                 "temperatureMax": 59.35,
                 "temperatureMaxTime": 1581202860,
                 "apparentTemperatureMin": 47.71,
                 "apparentTemperatureMinTime": 1581176460,
                 "apparentTemperatureMax": 58.85,
                 "apparentTemperatureMaxTime": 1581202860
             },
             {
                 "time": 1581235200,
                 "summary": "Windy starting in the afternoon.",
                 "icon": "wind",
                 "sunriseTime": 1581260880,
                 "sunsetTime": 1581298980,
                 "moonPhase": 0.53,
                 "precipIntensity": 0,
                 "precipIntensityMax": 0.0003,
                 "precipIntensityMaxTime": 1581282000,
                 "precipProbability": 0.02,
                 "temperatureHigh": 59.6,
                 "temperatureHighTime": 1581292860,
                 "temperatureLow": 51.09,
                 "temperatureLowTime": 1581345600,
                 "apparentTemperatureHigh": 59.1,
                 "apparentTemperatureHighTime": 1581292860,
                 "apparentTemperatureLow": 51.58,
                 "apparentTemperatureLowTime": 1581345600,
                 "dewPoint": 29.86,
                 "humidity": 0.44,
                 "pressure": 1012.5,
                 "windSpeed": 16.96,
                 "windGust": 43.86,
                 "windGustTime": 1581303480,
                 "windBearing": 4,
                 "cloudCover": 0,
                 "uvIndex": 3,
                 "uvIndexTime": 1581279780,
                 "visibility": 10,
                 "ozone": 340.8,
                 "temperatureMin": 46.14,
                 "temperatureMinTime": 1581259500,
                 "temperatureMax": 59.6,
                 "temperatureMaxTime": 1581292860,
                 "apparentTemperatureMin": 40.99,
                 "apparentTemperatureMinTime": 1581260460,
                 "apparentTemperatureMax": 59.1,
                 "apparentTemperatureMaxTime": 1581292860
             },
             {
                 "time": 1581321600,
                 "summary": "Windy in the morning.",
                 "icon": "wind",
                 "sunriseTime": 1581347220,
                 "sunsetTime": 1581385440,
                 "moonPhase": 0.57,
                 "precipIntensity": 0.0001,
                 "precipIntensityMax": 0.0003,
                 "precipIntensityMaxTime": 1581361200,
                 "precipProbability": 0.04,
                 "precipType": "rain",
                 "temperatureHigh": 63.82,
                 "temperatureHighTime": 1581377940,
                 "temperatureLow": 48.6,
                 "temperatureLowTime": 1581432900,
                 "apparentTemperatureHigh": 63.32,
                 "apparentTemperatureHighTime": 1581377940,
                 "apparentTemperatureLow": 46.88,
                 "apparentTemperatureLowTime": 1581432300,
                 "dewPoint": 23.16,
                 "humidity": 0.27,
                 "pressure": 1013.7,
                 "windSpeed": 16.79,
                 "windGust": 41.3,
                 "windGustTime": 1581342780,
                 "windBearing": 14,
                 "cloudCover": 0,
                 "uvIndex": 3,
                 "uvIndexTime": 1581366240,
                 "visibility": 10,
                 "ozone": 349.5,
                 "temperatureMin": 51.09,
                 "temperatureMinTime": 1581345600,
                 "temperatureMax": 63.82,
                 "temperatureMaxTime": 1581377940,
                 "apparentTemperatureMin": 51.58,
                 "apparentTemperatureMinTime": 1581345600,
                 "apparentTemperatureMax": 63.32,
                 "apparentTemperatureMaxTime": 1581377940
             },
             {
                 "time": 1581408000,
                 "summary": "Clear throughout the day.",
                 "icon": "clear-day",
                 "sunriseTime": 1581433500,
                 "sunsetTime": 1581471900,
                 "moonPhase": 0.61,
                 "precipIntensity": 0,
                 "precipIntensityMax": 0.0002,
                 "precipIntensityMaxTime": 1581423900,
                 "precipProbability": 0.03,
                 "temperatureHigh": 60.03,
                 "temperatureHighTime": 1581460020,
                 "temperatureLow": 47.03,
                 "temperatureLowTime": 1581518580,
                 "apparentTemperatureHigh": 59.53,
                 "apparentTemperatureHighTime": 1581460020,
                 "apparentTemperatureLow": 43.4,
                 "apparentTemperatureLowTime": 1581518100,
                 "dewPoint": 35.54,
                 "humidity": 0.53,
                 "pressure": 1014.1,
                 "windSpeed": 6.44,
                 "windGust": 15.31,
                 "windGustTime": 1581408000,
                 "windBearing": 33,
                 "cloudCover": 0,
                 "uvIndex": 4,
                 "uvIndexTime": 1581452640,
                 "visibility": 10,
                 "ozone": 323.4,
                 "temperatureMin": 48.6,
                 "temperatureMinTime": 1581432900,
                 "temperatureMax": 60.03,
                 "temperatureMaxTime": 1581460020,
                 "apparentTemperatureMin": 46.88,
                 "apparentTemperatureMinTime": 1581432300,
                 "apparentTemperatureMax": 59.53,
                 "apparentTemperatureMaxTime": 1581460020
             }
         ]
     },
     "flags": {
         "sources": [
             "nwspa",
             "cmc",
             "gfs",
             "hrrr",
             "icon",
             "isd",
             "madis",
             "nam",
             "sref",
             "darksky",
             "nearest-precip"
         ],
         "nearest-station": 2.24,
         "units": "us"
     },
     "offset": -8
 }
 */
