//
//  exampleData.swift
//  WeatherAppTests
//
//  Created by Pursuit on 2/3/20.
//  Copyright © 2020 David Rifkin. All rights reserved.
//

import Foundation
/*
{
    "latitude": 37.8267,
    "longitude": -122.4233,
    "timezone": "America/Los_Angeles",
    "currently": {
        "time": 1580762118,
        "summary": "Clear",
        "icon": "clear-day",
        "nearestStormDistance": 1,
        "nearestStormBearing": 180,
        "precipIntensity": 0,
        "precipProbability": 0,
        "temperature": 52.22,
        "apparentTemperature": 52.43,
        "dewPoint": 22.49,
        "humidity": 0.31,
        "pressure": 1021.3,
        "windSpeed": 12.51,
        "windGust": 18.16,
        "windBearing": 2,
        "cloudCover": 0,
        "uvIndex": 3,
        "visibility": 10,
        "ozone": 354.1
    },
    "minutely": {
        "summary": "Clear for the hour.",
        "icon": "clear-day",
        "data": [
            {
                "time": 1580762100,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580762160,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580762220,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580762280,
                "precipIntensity": 0.003,
                "precipIntensityError": 0.002,
                "precipProbability": 0.01,
                "precipType": "rain"
            },
            {
                "time": 1580762340,
                "precipIntensity": 0.004,
                "precipIntensityError": 0.002,
                "precipProbability": 0.01,
                "precipType": "rain"
            },
            {
                "time": 1580762400,
                "precipIntensity": 0.004,
                "precipIntensityError": 0.003,
                "precipProbability": 0.02,
                "precipType": "rain"
            },
            {
                "time": 1580762460,
                "precipIntensity": 0.004,
                "precipIntensityError": 0.003,
                "precipProbability": 0.03,
                "precipType": "rain"
            },
            {
                "time": 1580762520,
                "precipIntensity": 0.004,
                "precipIntensityError": 0.003,
                "precipProbability": 0.03,
                "precipType": "rain"
            },
            {
                "time": 1580762580,
                "precipIntensity": 0.005,
                "precipIntensityError": 0.004,
                "precipProbability": 0.04,
                "precipType": "rain"
            },
            {
                "time": 1580762640,
                "precipIntensity": 0.005,
                "precipIntensityError": 0.004,
                "precipProbability": 0.05,
                "precipType": "rain"
            },
            {
                "time": 1580762700,
                "precipIntensity": 0.005,
                "precipIntensityError": 0.003,
                "precipProbability": 0.06,
                "precipType": "rain"
            },
            {
                "time": 1580762760,
                "precipIntensity": 0.005,
                "precipIntensityError": 0.004,
                "precipProbability": 0.07,
                "precipType": "rain"
            },
            {
                "time": 1580762820,
                "precipIntensity": 0.005,
                "precipIntensityError": 0.004,
                "precipProbability": 0.08,
                "precipType": "rain"
            },
            {
                "time": 1580762880,
                "precipIntensity": 0.005,
                "precipIntensityError": 0.004,
                "precipProbability": 0.08,
                "precipType": "rain"
            },
            {
                "time": 1580762940,
                "precipIntensity": 0.005,
                "precipIntensityError": 0.003,
                "precipProbability": 0.09,
                "precipType": "rain"
            },
            {
                "time": 1580763000,
                "precipIntensity": 0.005,
                "precipIntensityError": 0.003,
                "precipProbability": 0.1,
                "precipType": "rain"
            },
            {
                "time": 1580763060,
                "precipIntensity": 0.005,
                "precipIntensityError": 0.003,
                "precipProbability": 0.1,
                "precipType": "rain"
            },
            {
                "time": 1580763120,
                "precipIntensity": 0.005,
                "precipIntensityError": 0.004,
                "precipProbability": 0.11,
                "precipType": "rain"
            },
            {
                "time": 1580763180,
                "precipIntensity": 0.005,
                "precipIntensityError": 0.003,
                "precipProbability": 0.11,
                "precipType": "rain"
            },
            {
                "time": 1580763240,
                "precipIntensity": 0.005,
                "precipIntensityError": 0.004,
                "precipProbability": 0.11,
                "precipType": "rain"
            },
            {
                "time": 1580763300,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580763360,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580763420,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580763480,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580763540,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580763600,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580763660,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580763720,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580763780,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580763840,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580763900,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580763960,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764020,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764080,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764140,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764200,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764260,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764320,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764380,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764440,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764500,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764560,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764620,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764680,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764740,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764800,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764860,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764920,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580764980,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580765040,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580765100,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580765160,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580765220,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580765280,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580765340,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580765400,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580765460,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580765520,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580765580,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580765640,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1580765700,
                "precipIntensity": 0,
                "precipProbability": 0
            }
        ]
    },
    "hourly": {
        "summary": "Clear throughout the day.",
        "icon": "clear-day",
        "data": [
            {
                "time": 1580760000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 51.47,
                "apparentTemperature": 51.47,
                "dewPoint": 24.62,
                "humidity": 0.35,
                "pressure": 1021.5,
                "windSpeed": 11.82,
                "windGust": 18.04,
                "windBearing": 0,
                "cloudCover": 0.01,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 354.8
            },
            {
                "time": 1580763600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0014,
                "precipProbability": 0.11,
                "precipType": "rain",
                "temperature": 52.73,
                "apparentTemperature": 52.73,
                "dewPoint": 20.97,
                "humidity": 0.29,
                "pressure": 1021.2,
                "windSpeed": 12.9,
                "windGust": 18.26,
                "windBearing": 2,
                "cloudCover": 0,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 353.6
            },
            {
                "time": 1580767200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0013,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 54.38,
                "apparentTemperature": 54.38,
                "dewPoint": 17.27,
                "humidity": 0.23,
                "pressure": 1020.8,
                "windSpeed": 13.42,
                "windGust": 18.75,
                "windBearing": 2,
                "cloudCover": 0,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 351.7
            },
            {
                "time": 1580770800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0011,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 55.54,
                "apparentTemperature": 55.54,
                "dewPoint": 14.99,
                "humidity": 0.2,
                "pressure": 1020.8,
                "windSpeed": 13.86,
                "windGust": 19.16,
                "windBearing": 358,
                "cloudCover": 0,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 349.4
            },
            {
                "time": 1580774400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 55.25,
                "apparentTemperature": 55.25,
                "dewPoint": 16.66,
                "humidity": 0.22,
                "pressure": 1019.9,
                "windSpeed": 13.88,
                "windGust": 18.79,
                "windBearing": 353,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 347.6
            },
            {
                "time": 1580778000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0019,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 54.09,
                "apparentTemperature": 54.09,
                "dewPoint": 19.47,
                "humidity": 0.25,
                "pressure": 1021.3,
                "windSpeed": 13.2,
                "windGust": 18.58,
                "windBearing": 349,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 346.5
            },
            {
                "time": 1580781600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 52.02,
                "apparentTemperature": 52.02,
                "dewPoint": 22.49,
                "humidity": 0.31,
                "pressure": 1020.9,
                "windSpeed": 12.17,
                "windGust": 18.88,
                "windBearing": 346,
                "cloudCover": 0.07,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 345.8
            },
            {
                "time": 1580785200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 50.48,
                "apparentTemperature": 50.48,
                "dewPoint": 24.77,
                "humidity": 0.36,
                "pressure": 1021,
                "windSpeed": 11.52,
                "windGust": 18.74,
                "windBearing": 345,
                "cloudCover": 0.11,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 345.9
            },
            {
                "time": 1580788800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 49.43,
                "apparentTemperature": 44.76,
                "dewPoint": 25.16,
                "humidity": 0.38,
                "pressure": 1022.2,
                "windSpeed": 11.83,
                "windGust": 20.66,
                "windBearing": 348,
                "cloudCover": 0.33,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 347.1
            },
            {
                "time": 1580792400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 48.73,
                "apparentTemperature": 43.7,
                "dewPoint": 24.33,
                "humidity": 0.38,
                "pressure": 1021.5,
                "windSpeed": 12.44,
                "windGust": 22.13,
                "windBearing": 352,
                "cloudCover": 0.23,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 348.9
            },
            {
                "time": 1580796000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 48.12,
                "apparentTemperature": 42.76,
                "dewPoint": 23.65,
                "humidity": 0.38,
                "pressure": 1021.9,
                "windSpeed": 13.01,
                "windGust": 23.19,
                "windBearing": 357,
                "cloudCover": 0.12,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 350.9
            },
            {
                "time": 1580799600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 47.6,
                "apparentTemperature": 42.02,
                "dewPoint": 23.82,
                "humidity": 0.39,
                "pressure": 1022.1,
                "windSpeed": 13.3,
                "windGust": 23.43,
                "windBearing": 359,
                "cloudCover": 0.36,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 353.1
            },
            {
                "time": 1580803200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 47.22,
                "apparentTemperature": 41.45,
                "dewPoint": 24.01,
                "humidity": 0.4,
                "pressure": 1022.7,
                "windSpeed": 13.62,
                "windGust": 23.59,
                "windBearing": 358,
                "cloudCover": 0.03,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 355.4
            },
            {
                "time": 1580806800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 46.85,
                "apparentTemperature": 40.9,
                "dewPoint": 24.73,
                "humidity": 0.42,
                "pressure": 1022.7,
                "windSpeed": 13.89,
                "windGust": 23.78,
                "windBearing": 0,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 357
            },
            {
                "time": 1580810400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 46.34,
                "apparentTemperature": 40.24,
                "dewPoint": 25.83,
                "humidity": 0.44,
                "pressure": 1023.1,
                "windSpeed": 13.97,
                "windGust": 23.81,
                "windBearing": 1,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 357.4
            },
            {
                "time": 1580814000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 45.87,
                "apparentTemperature": 39.28,
                "dewPoint": 25.67,
                "humidity": 0.45,
                "pressure": 1023.6,
                "windSpeed": 15.28,
                "windGust": 24.34,
                "windBearing": 8,
                "cloudCover": 0.01,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 357.1
            },
            {
                "time": 1580817600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 45.1,
                "apparentTemperature": 38.35,
                "dewPoint": 26.61,
                "humidity": 0.48,
                "pressure": 1023.9,
                "windSpeed": 15.07,
                "windGust": 23.32,
                "windBearing": 9,
                "cloudCover": 0.02,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 357.1
            },
            {
                "time": 1580821200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 44.12,
                "apparentTemperature": 37.29,
                "dewPoint": 27.07,
                "humidity": 0.51,
                "pressure": 1023.6,
                "windSpeed": 14.39,
                "windGust": 21.36,
                "windBearing": 9,
                "cloudCover": 0.04,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 357.5
            },
            {
                "time": 1580824800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 43.44,
                "apparentTemperature": 36.7,
                "dewPoint": 27.14,
                "humidity": 0.52,
                "pressure": 1022.8,
                "windSpeed": 13.44,
                "windGust": 18.89,
                "windBearing": 10,
                "cloudCover": 0.06,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 358
            },
            {
                "time": 1580828400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 43.29,
                "apparentTemperature": 36.77,
                "dewPoint": 26.79,
                "humidity": 0.52,
                "pressure": 1023,
                "windSpeed": 12.64,
                "windGust": 17.38,
                "windBearing": 11,
                "cloudCover": 0.07,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 359.2
            },
            {
                "time": 1580832000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 44.05,
                "apparentTemperature": 37.86,
                "dewPoint": 26.06,
                "humidity": 0.49,
                "pressure": 1023.5,
                "windSpeed": 12.24,
                "windGust": 17.85,
                "windBearing": 13,
                "cloudCover": 0.08,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 361.5
            },
            {
                "time": 1580835600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 45.63,
                "apparentTemperature": 39.93,
                "dewPoint": 24.89,
                "humidity": 0.44,
                "pressure": 1024.8,
                "windSpeed": 12,
                "windGust": 19.17,
                "windBearing": 15,
                "cloudCover": 0.08,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 364.4
            },
            {
                "time": 1580839200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 47.34,
                "apparentTemperature": 42.16,
                "dewPoint": 23.5,
                "humidity": 0.39,
                "pressure": 1025.3,
                "windSpeed": 11.73,
                "windGust": 19.63,
                "windBearing": 16,
                "cloudCover": 0.09,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 366.4
            },
            {
                "time": 1580842800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 49.28,
                "apparentTemperature": 44.7,
                "dewPoint": 21.91,
                "humidity": 0.34,
                "pressure": 1025,
                "windSpeed": 11.37,
                "windGust": 18.38,
                "windBearing": 15,
                "cloudCover": 0.11,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 366.7
            },
            {
                "time": 1580846400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 51.69,
                "apparentTemperature": 51.69,
                "dewPoint": 20.12,
                "humidity": 0.29,
                "pressure": 1024.6,
                "windSpeed": 10.97,
                "windGust": 16.38,
                "windBearing": 12,
                "cloudCover": 0.15,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 366.1
            },
            {
                "time": 1580850000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 53.7,
                "apparentTemperature": 53.7,
                "dewPoint": 19.05,
                "humidity": 0.25,
                "pressure": 1024,
                "windSpeed": 10.55,
                "windGust": 14.58,
                "windBearing": 9,
                "cloudCover": 0.18,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 365.9
            },
            {
                "time": 1580853600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 55.09,
                "apparentTemperature": 55.09,
                "dewPoint": 19.49,
                "humidity": 0.25,
                "pressure": 1023.4,
                "windSpeed": 10.11,
                "windGust": 13.38,
                "windBearing": 4,
                "cloudCover": 0.19,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 367.2
            },
            {
                "time": 1580857200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 56.02,
                "apparentTemperature": 56.02,
                "dewPoint": 21.27,
                "humidity": 0.26,
                "pressure": 1022.8,
                "windSpeed": 9.66,
                "windGust": 12.36,
                "windBearing": 355,
                "cloudCover": 0.21,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 368.9
            },
            {
                "time": 1580860800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 56.05,
                "apparentTemperature": 56.05,
                "dewPoint": 23.53,
                "humidity": 0.28,
                "pressure": 1022.1,
                "windSpeed": 9.22,
                "windGust": 11.42,
                "windBearing": 348,
                "cloudCover": 0.2,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 369.8
            },
            {
                "time": 1580864400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 54.7,
                "apparentTemperature": 54.7,
                "dewPoint": 26.3,
                "humidity": 0.33,
                "pressure": 1022.2,
                "windSpeed": 8.81,
                "windGust": 10.66,
                "windBearing": 342,
                "cloudCover": 0.18,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 369.1
            },
            {
                "time": 1580868000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 52.77,
                "apparentTemperature": 52.77,
                "dewPoint": 29.03,
                "humidity": 0.4,
                "pressure": 1022.7,
                "windSpeed": 8.38,
                "windGust": 9.91,
                "windBearing": 337,
                "cloudCover": 0.15,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 367.6
            },
            {
                "time": 1580871600,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 51.14,
                "apparentTemperature": 51.14,
                "dewPoint": 30.93,
                "humidity": 0.46,
                "pressure": 1023.1,
                "windSpeed": 7.78,
                "windGust": 8.84,
                "windBearing": 337,
                "cloudCover": 0.13,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 366.3
            },
            {
                "time": 1580875200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 50.28,
                "apparentTemperature": 50.28,
                "dewPoint": 32.15,
                "humidity": 0.5,
                "pressure": 1023.4,
                "windSpeed": 6.95,
                "windGust": 7.25,
                "windBearing": 338,
                "cloudCover": 0.14,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 365.6
            },
            {
                "time": 1580878800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 49.76,
                "apparentTemperature": 47.38,
                "dewPoint": 33.25,
                "humidity": 0.53,
                "pressure": 1024.2,
                "windSpeed": 6,
                "windGust": 6,
                "windBearing": 342,
                "cloudCover": 0.15,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 365.1
            },
            {
                "time": 1580882400,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 49.27,
                "apparentTemperature": 47.23,
                "dewPoint": 34.12,
                "humidity": 0.56,
                "pressure": 1024.6,
                "windSpeed": 5.21,
                "windGust": 5.21,
                "windBearing": 348,
                "cloudCover": 0.18,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 364.5
            },
            {
                "time": 1580886000,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 48.82,
                "apparentTemperature": 47.06,
                "dewPoint": 34.77,
                "humidity": 0.58,
                "pressure": 1024.7,
                "windSpeed": 4.64,
                "windGust": 4.64,
                "windBearing": 5,
                "cloudCover": 0.25,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 363.6
            },
            {
                "time": 1580889600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 48.48,
                "apparentTemperature": 46.96,
                "dewPoint": 35.25,
                "humidity": 0.6,
                "pressure": 1024.8,
                "windSpeed": 4.21,
                "windGust": 4.21,
                "windBearing": 17,
                "cloudCover": 0.34,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 362.6
            },
            {
                "time": 1580893200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 48.08,
                "apparentTemperature": 46.66,
                "dewPoint": 35.47,
                "humidity": 0.62,
                "pressure": 1024.9,
                "windSpeed": 3.99,
                "windGust": 3.99,
                "windBearing": 20,
                "cloudCover": 0.41,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 361.5
            },
            {
                "time": 1580896800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 47.57,
                "apparentTemperature": 45.99,
                "dewPoint": 35.39,
                "humidity": 0.62,
                "pressure": 1024.9,
                "windSpeed": 4.09,
                "windGust": 4.09,
                "windBearing": 33,
                "cloudCover": 0.47,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 360.4
            },
            {
                "time": 1580900400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 47.04,
                "apparentTemperature": 45.15,
                "dewPoint": 34.94,
                "humidity": 0.63,
                "pressure": 1025,
                "windSpeed": 4.41,
                "windGust": 4.41,
                "windBearing": 41,
                "cloudCover": 0.51,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 359.3
            },
            {
                "time": 1580904000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 46.31,
                "apparentTemperature": 44.11,
                "dewPoint": 34.35,
                "humidity": 0.63,
                "pressure": 1025.1,
                "windSpeed": 4.66,
                "windGust": 4.66,
                "windBearing": 47,
                "cloudCover": 0.54,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 357.2
            },
            {
                "time": 1580907600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 45.43,
                "apparentTemperature": 43.03,
                "dewPoint": 33.49,
                "humidity": 0.63,
                "pressure": 1025.3,
                "windSpeed": 4.74,
                "windGust": 4.82,
                "windBearing": 52,
                "cloudCover": 0.56,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 353.4
            },
            {
                "time": 1580911200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 44.59,
                "apparentTemperature": 42.04,
                "dewPoint": 32.57,
                "humidity": 0.63,
                "pressure": 1025.3,
                "windSpeed": 4.75,
                "windGust": 5.08,
                "windBearing": 56,
                "cloudCover": 0.57,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 348.9
            },
            {
                "time": 1580914800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 44.63,
                "apparentTemperature": 42.05,
                "dewPoint": 31.65,
                "humidity": 0.6,
                "pressure": 1025.5,
                "windSpeed": 4.79,
                "windGust": 5.39,
                "windBearing": 57,
                "cloudCover": 0.55,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 345.9
            },
            {
                "time": 1580918400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 45.89,
                "apparentTemperature": 43.44,
                "dewPoint": 30.12,
                "humidity": 0.54,
                "pressure": 1025.4,
                "windSpeed": 4.93,
                "windGust": 5.42,
                "windBearing": 56,
                "cloudCover": 0.51,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 346.6
            },
            {
                "time": 1580922000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 48.08,
                "apparentTemperature": 45.89,
                "dewPoint": 28.11,
                "humidity": 0.46,
                "pressure": 1025.6,
                "windSpeed": 5.11,
                "windGust": 5.64,
                "windBearing": 53,
                "cloudCover": 0.46,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 348.9
            },
            {
                "time": 1580925600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 50.06,
                "apparentTemperature": 50.06,
                "dewPoint": 26.72,
                "humidity": 0.4,
                "pressure": 1025.7,
                "windSpeed": 5.17,
                "windGust": 5.8,
                "windBearing": 45,
                "cloudCover": 0.39,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 349.3
            },
            {
                "time": 1580929200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 52.45,
                "apparentTemperature": 52.45,
                "dewPoint": 26.38,
                "humidity": 0.36,
                "pressure": 1025.4,
                "windSpeed": 5.01,
                "windGust": 5.73,
                "windBearing": 26,
                "cloudCover": 0.28,
                "uvIndex": 2,
                "visibility": 10,
                "ozone": 346.3
            },
            {
                "time": 1580932800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 54.86,
                "apparentTemperature": 54.86,
                "dewPoint": 26.93,
                "humidity": 0.34,
                "pressure": 1024.9,
                "windSpeed": 4.75,
                "windGust": 6.03,
                "windBearing": 2,
                "cloudCover": 0.15,
                "uvIndex": 3,
                "visibility": 10,
                "ozone": 341.3
            }
        ]
    },
    "daily": {
        "summary": "No precipitation throughout the week.",
        "icon": "clear-day",
        "data": [
            {
                "time": 1580716800,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1580742780,
                "sunsetTime": 1580780160,
                "moonPhase": 0.32,
                "precipIntensity": 0.0006,
                "precipIntensityMax": 0.0021,
                "precipIntensityMaxTime": 1580755980,
                "precipProbability": 0.1,
                "precipType": "rain",
                "temperatureHigh": 56.09,
                "temperatureHighTime": 1580771640,
                "temperatureLow": 42.76,
                "temperatureLowTime": 1580827440,
                "apparentTemperatureHigh": 55.59,
                "apparentTemperatureHighTime": 1580771640,
                "apparentTemperatureLow": 36.63,
                "apparentTemperatureLowTime": 1580826540,
                "dewPoint": 26.61,
                "humidity": 0.46,
                "pressure": 1021.3,
                "windSpeed": 11.23,
                "windGust": 23.59,
                "windGustTime": 1580803200,
                "windBearing": 348,
                "cloudCover": 0.07,
                "uvIndex": 3,
                "uvIndexTime": 1580761500,
                "visibility": 10,
                "ozone": 354,
                "temperatureMin": 42.18,
                "temperatureMinTime": 1580741700,
                "temperatureMax": 56.09,
                "temperatureMaxTime": 1580771640,
                "apparentTemperatureMin": 37.37,
                "apparentTemperatureMinTime": 1580739180,
                "apparentTemperatureMax": 55.59,
                "apparentTemperatureMaxTime": 1580771640
            },
            {
                "time": 1580803200,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1580829180,
                "sunsetTime": 1580866620,
                "moonPhase": 0.35,
                "precipIntensity": 0.0001,
                "precipIntensityMax": 0.0003,
                "precipIntensityMaxTime": 1580848380,
                "precipProbability": 0.05,
                "precipType": "rain",
                "temperatureHigh": 56.68,
                "temperatureHighTime": 1580859240,
                "temperatureLow": 43.99,
                "temperatureLowTime": 1580913000,
                "apparentTemperatureHigh": 56.18,
                "apparentTemperatureHighTime": 1580859240,
                "apparentTemperatureLow": 41.9,
                "apparentTemperatureLowTime": 1580913060,
                "dewPoint": 26.41,
                "humidity": 0.42,
                "pressure": 1023.6,
                "windSpeed": 10.55,
                "windGust": 24.35,
                "windGustTime": 1580813760,
                "windBearing": 3,
                "cloudCover": 0.12,
                "uvIndex": 3,
                "uvIndexTime": 1580847660,
                "visibility": 10,
                "ozone": 363.4,
                "temperatureMin": 42.76,
                "temperatureMinTime": 1580827440,
                "temperatureMax": 56.68,
                "temperatureMaxTime": 1580859240,
                "apparentTemperatureMin": 36.63,
                "apparentTemperatureMinTime": 1580826540,
                "apparentTemperatureMax": 56.18,
                "apparentTemperatureMaxTime": 1580859240
            },
            {
                "time": 1580889600,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1580915520,
                "sunsetTime": 1580953080,
                "moonPhase": 0.39,
                "precipIntensity": 0.0001,
                "precipIntensityMax": 0.0004,
                "precipIntensityMaxTime": 1580976000,
                "precipProbability": 0.05,
                "precipType": "rain",
                "temperatureHigh": 59.89,
                "temperatureHighTime": 1580944440,
                "temperatureLow": 45.84,
                "temperatureLowTime": 1581001080,
                "apparentTemperatureHigh": 59.39,
                "apparentTemperatureHighTime": 1580944440,
                "apparentTemperatureLow": 44.04,
                "apparentTemperatureLowTime": 1581000660,
                "dewPoint": 35.81,
                "humidity": 0.57,
                "pressure": 1024.5,
                "windSpeed": 5.07,
                "windGust": 6.8,
                "windGustTime": 1580954100,
                "windBearing": 345,
                "cloudCover": 0.29,
                "uvIndex": 3,
                "uvIndexTime": 1580935080,
                "visibility": 10,
                "ozone": 331.6,
                "temperatureMin": 43.99,
                "temperatureMinTime": 1580913000,
                "temperatureMax": 59.89,
                "temperatureMaxTime": 1580944440,
                "apparentTemperatureMin": 41.9,
                "apparentTemperatureMinTime": 1580913060,
                "apparentTemperatureMax": 59.39,
                "apparentTemperatureMaxTime": 1580944440
            },
            {
                "time": 1580976000,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1581001860,
                "sunsetTime": 1581039540,
                "moonPhase": 0.42,
                "precipIntensity": 0.0005,
                "precipIntensityMax": 0.0022,
                "precipIntensityMaxTime": 1580990460,
                "precipProbability": 0.1,
                "precipType": "rain",
                "temperatureHigh": 59.93,
                "temperatureHighTime": 1581030660,
                "temperatureLow": 45.62,
                "temperatureLowTime": 1581086820,
                "apparentTemperatureHigh": 59.43,
                "apparentTemperatureHighTime": 1581030660,
                "apparentTemperatureLow": 43.41,
                "apparentTemperatureLowTime": 1581087240,
                "dewPoint": 45.07,
                "humidity": 0.78,
                "pressure": 1022.3,
                "windSpeed": 4.75,
                "windGust": 7.37,
                "windGustTime": 1581043620,
                "windBearing": 332,
                "cloudCover": 0.21,
                "uvIndex": 3,
                "uvIndexTime": 1581020880,
                "visibility": 10,
                "ozone": 288.3,
                "temperatureMin": 45.84,
                "temperatureMinTime": 1581001080,
                "temperatureMax": 59.93,
                "temperatureMaxTime": 1581030660,
                "apparentTemperatureMin": 44.04,
                "apparentTemperatureMinTime": 1581000660,
                "apparentTemperatureMax": 59.43,
                "apparentTemperatureMaxTime": 1581030660
            },
            {
                "time": 1581062400,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1581088200,
                "sunsetTime": 1581126060,
                "moonPhase": 0.46,
                "precipIntensity": 0.0001,
                "precipIntensityMax": 0.0003,
                "precipIntensityMaxTime": 1581091200,
                "precipProbability": 0.06,
                "precipType": "rain",
                "temperatureHigh": 61.63,
                "temperatureHighTime": 1581117000,
                "temperatureLow": 48.63,
                "temperatureLowTime": 1581171540,
                "apparentTemperatureHigh": 61.13,
                "apparentTemperatureHighTime": 1581117000,
                "apparentTemperatureLow": 47.99,
                "apparentTemperatureLowTime": 1581172440,
                "dewPoint": 46.43,
                "humidity": 0.81,
                "pressure": 1019.8,
                "windSpeed": 4.86,
                "windGust": 9.22,
                "windGustTime": 1581108540,
                "windBearing": 11,
                "cloudCover": 0,
                "uvIndex": 4,
                "uvIndexTime": 1581107040,
                "visibility": 10,
                "ozone": 290.3,
                "temperatureMin": 45.62,
                "temperatureMinTime": 1581086820,
                "temperatureMax": 61.63,
                "temperatureMaxTime": 1581117000,
                "apparentTemperatureMin": 43.41,
                "apparentTemperatureMinTime": 1581087240,
                "apparentTemperatureMax": 61.13,
                "apparentTemperatureMaxTime": 1581117000
            },
            {
                "time": 1581148800,
                "summary": "Mostly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1581174540,
                "sunsetTime": 1581212520,
                "moonPhase": 0.5,
                "precipIntensity": 0.0001,
                "precipIntensityMax": 0.0003,
                "precipIntensityMaxTime": 1581206280,
                "precipProbability": 0.06,
                "precipType": "rain",
                "temperatureHigh": 58.01,
                "temperatureHighTime": 1581200820,
                "temperatureLow": 47.44,
                "temperatureLowTime": 1581258660,
                "apparentTemperatureHigh": 57.51,
                "apparentTemperatureHighTime": 1581200820,
                "apparentTemperatureLow": 42.78,
                "apparentTemperatureLowTime": 1581259380,
                "dewPoint": 49.63,
                "humidity": 0.9,
                "pressure": 1018.6,
                "windSpeed": 5.01,
                "windGust": 8.18,
                "windGustTime": 1581207180,
                "windBearing": 298,
                "cloudCover": 0.63,
                "uvIndex": 3,
                "uvIndexTime": 1581192300,
                "visibility": 10,
                "ozone": 303.2,
                "temperatureMin": 48.63,
                "temperatureMinTime": 1581171540,
                "temperatureMax": 58.01,
                "temperatureMaxTime": 1581200820,
                "apparentTemperatureMin": 47.99,
                "apparentTemperatureMinTime": 1581172440,
                "apparentTemperatureMax": 57.51,
                "apparentTemperatureMaxTime": 1581200820
            },
            {
                "time": 1581235200,
                "summary": "Windy in the evening.",
                "icon": "wind",
                "sunriseTime": 1581260880,
                "sunsetTime": 1581298980,
                "moonPhase": 0.53,
                "precipIntensity": 0.0001,
                "precipIntensityMax": 0.0004,
                "precipIntensityMaxTime": 1581309300,
                "precipProbability": 0.07,
                "precipType": "rain",
                "temperatureHigh": 60.81,
                "temperatureHighTime": 1581292500,
                "temperatureLow": 52.53,
                "temperatureLowTime": 1581345300,
                "apparentTemperatureHigh": 60.31,
                "apparentTemperatureHighTime": 1581292500,
                "apparentTemperatureLow": 53.02,
                "apparentTemperatureLowTime": 1581345300,
                "dewPoint": 37.07,
                "humidity": 0.57,
                "pressure": 1014,
                "windSpeed": 14.58,
                "windGust": 39.85,
                "windGustTime": 1581304920,
                "windBearing": 351,
                "cloudCover": 0.37,
                "uvIndex": 3,
                "uvIndexTime": 1581279840,
                "visibility": 10,
                "ozone": 343.9,
                "temperatureMin": 47.44,
                "temperatureMinTime": 1581258660,
                "temperatureMax": 60.81,
                "temperatureMaxTime": 1581292500,
                "apparentTemperatureMin": 42.78,
                "apparentTemperatureMinTime": 1581259380,
                "apparentTemperatureMax": 60.31,
                "apparentTemperatureMaxTime": 1581292500
            },
            {
                "time": 1581321600,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1581347220,
                "sunsetTime": 1581385440,
                "moonPhase": 0.57,
                "precipIntensity": 0.0001,
                "precipIntensityMax": 0.0003,
                "precipIntensityMaxTime": 1581402300,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperatureHigh": 64.56,
                "temperatureHighTime": 1581376440,
                "temperatureLow": 46.47,
                "temperatureLowTime": 1581432060,
                "apparentTemperatureHigh": 64.06,
                "apparentTemperatureHighTime": 1581376440,
                "apparentTemperatureLow": 43.31,
                "apparentTemperatureLowTime": 1581434640,
                "dewPoint": 32.41,
                "humidity": 0.41,
                "pressure": 1012.4,
                "windSpeed": 11.82,
                "windGust": 37.55,
                "windGustTime": 1581322560,
                "windBearing": 3,
                "cloudCover": 0,
                "uvIndex": 3,
                "uvIndexTime": 1581366360,
                "visibility": 10,
                "ozone": 367.6,
                "temperatureMin": 51.31,
                "temperatureMinTime": 1581408000,
                "temperatureMax": 64.56,
                "temperatureMaxTime": 1581376440,
                "apparentTemperatureMin": 51.8,
                "apparentTemperatureMinTime": 1581408000,
                "apparentTemperatureMax": 64.06,
                "apparentTemperatureMaxTime": 1581376440
            }
        ]
    },
    "flags": {
        "sources": [
            "nwspa",
            "cmc",
            "gfs",
            "hrrr",
            "icon",
            "isd",
            "madis",
            "nam",
            "sref",
            "darksky",
            "nearest-precip"
        ],
        "nearest-station": 2.24,
        "units": "us"
    },
    "offset": -8
}

 */
